//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public string UserId { get; set; }
        public string Origin { get; set; }
        public string OriginCoordinates { get; set; }
        public string Destination { get; set; }
        public string DestinationCoordinates { get; set; }
        public string RouteLength { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
